[package]
name = "gbx"
version = "1.0.1"
edition = "2021"
license = "MIT"
description = "GBX (Grundbuch-Exchange) Dateiformat"

[dependencies]
lazy_static = "1.4.0"
regex = "1.7.3"
serde = { version = "1", features = ["derive"] }
